accounts/urls.py
# The views used below are normally mapped in the AdminSite instance.
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.contrib.auth import views
from django.urls import path
from .views import (
    HomeView,
    ArticleListView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    ArticlePreviewView,
    ProfileUpdateView,
    ArticleDetailView,
    CategoryListView,
    CategoryCreateView,
    CategoryDetailView,
    CategoryUpdateView, CategoryDeleteView, CommentListView, CommentUpdateView, CommentDeleteView, CommentAcceptView,
    LogEventsListView,
)

app_name = "accounts"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),

    path("articles/", ArticleListView.as_view(), name="list"),
    path("articles/create/", ArticleCreateView.as_view(), name="create"),
    path("articles/update/<int:pk>/", ArticleUpdateView.as_view(), name="update"),
    path("articles/delete/<int:pk>/", ArticleDeleteView.as_view(), name="delete"),
    path("articles/preview/<str:slug>/", ArticlePreviewView.as_view(), name="preview"),
    path("articles/detail/<str:slug>/", ArticleDetailView.as_view(), name="detail"),

    path("categories/", CategoryListView.as_view(), name="cat_list"),
    path("categories/create/", CategoryCreateView.as_view(), name="cat_create"),
    path("categories/detail/<str:slug>/", CategoryDetailView.as_view(), name="cat_detail"),
    path("categories/update/<int:pk>/", CategoryUpdateView.as_view(), name="cat_update"),
    path("categories/delete/<int:pk>/", CategoryDeleteView.as_view(), name="cat_delete"),

    path("comments/", CommentListView.as_view(), name="comment_list"),
    path("comments/update/<int:pk>/", CommentUpdateView.as_view(), name="comment_update"),
    path("comments/delete/<int:pk>/", CommentDeleteView.as_view(), name="comment_delete"),
    path("comments/accept/<int:pk>/", CommentAcceptView.as_view(), name="comment_accept"),

    path("profile/", ProfileUpdateView.as_view(), name="profile"),

    path("log/", LogEventsListView.as_view(), name="log")
]

api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from .views import ArticleListApiView, ArticleDetailApiView, UserListApiView, UserDetailApiView, RevokeTokenApiView,\
    CategoryListAPIView, CategoryDetailAPIVIEW
app_name = "api"

urlpatterns = [
    path("token/", obtain_auth_token, name="token"),
    path("revoke/", RevokeTokenApiView.as_view(), name="token"),
    path("", ArticleListApiView.as_view(), name="list"),
    path("detail/<str:slug>/", ArticleDetailApiView.as_view(), name="detail"),
    path("categories/", CategoryListAPIView.as_view(), name="cat_list"),
    path("categories/detail/<str:slug>/", CategoryDetailAPIVIEW.as_view(), name="cat_detail"),
    path("users/", UserListApiView.as_view(), name="user_list"),
    path("users/<int:pk>", UserDetailApiView.as_view(), name="user_detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from accounts.views import Login, RegisterPendingView, RegisterCompleteView
from accounts.views import RegisterCreateView, activate

handler500 = 'exception_handling.views.handler500'
handler404 = 'exception_handling.views.handler404'

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("register/", RegisterCreateView.as_view(), name="register"),
    path("register/pending/", RegisterPendingView.as_view(), name="register-pending"),
    path("register/complete/", RegisterCompleteView.as_view(), name="register-complete"),
    path("activate/<str:uidb64>/<str:token>/", activate, name="activate"),
    path("accounts/", include("accounts.urls"), name="home"),
    path("admin/doc/", include("django.contrib.admindocs.urls"), name="admin_doc"),
    path("admin/", admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path("api/", include("api.urls"), name="api"),
    path("pages/", include("pages.urls"), name="pages"),
    path("", include("django.contrib.auth.urls")),
    path("", include("blog.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.admin.models import LogEntry
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractUser

from extensions.utils import to_jalali


class User(AbstractUser):
    is_author = models.BooleanField(default=False, verbose_name="نویسنده")
    special_user = models.DateTimeField(
        default=timezone.now,
        verbose_name="ویژه تا",
    )
    email = models.EmailField(unique=True, verbose_name="ایمیل")

    def is_specialuser(self):
        if self.special_user > timezone.now() or self.is_superuser:
            return True
        return False

    is_specialuser.short_description = "کاربر ویژه"
    is_specialuser.boolean = True


class Logs(models.Model):
    class Meta:
        verbose_name = "رویداد"
        verbose_name_plural = "رویدادها"

    log = models.OneToOneField(LogEntry, on_delete=models.CASCADE, verbose_name="رویداد")

    def jpublished(self):
        return to_jalali(self.log.action_time)

    jpublished.short_description = "زمان رویداد"


@receiver(post_save, sender=LogEntry)
def create_medical_history(sender, instance, created, **kwargs):
    if created:
        Logs.objects.create(log=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super(ProfileForm, self).__init__(*args, **kwargs)
        if not user.is_superuser:
            self.fields["username"].disabled = True
            self.fields["is_author"].disabled = True
            self.fields["special_user"].disabled = True

    class Meta:
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "is_author",
            "special_user",
        ]
        model = User


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text="Required")

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

accounts/views.py
from django.http import request, HttpResponse
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic.list import ListView
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView
from django.template.loader import render_to_string
from .forms import SignupForm
from .tokens import account_activation_token
from blog.models import Blog, Category, Comment
from .models import User, Logs
from .forms import ProfileForm
from .mixins import FieldsMixin, FormValidMixin, UpdateAccessMixin, DraftEditMixin, DeleteArticleMixin, PreviewMixin,\
    AuthorsMixin, ActionMixin, StaffMixin


class Login(LoginView):
    template_name = "accounts/login.html"

    def get_success_url(self):
        if (
            self.request.user.is_superuser
            or self.request.user.is_staff
            or self.request.user.is_author
        ):
            return reverse_lazy("accounts:list")
        else:
            return reverse_lazy("accounts:profile")


class RegisterPendingView(TemplateView):
    template_name = "accounts/register_done.html"


class RegisterCompleteView(TemplateView):
    template_name = "accounts/register_complete.html"


class HomeView(LoginRequiredMixin, AuthorsMixin, TemplateView):
    template_name = "accounts/admin.html"


class ArticleListView(LoginRequiredMixin, AuthorsMixin, ListView):
    template_name = "accounts/articleList.html"

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Blog.objects.all()
        else:
            return Blog.objects.filter(author=self.request.user)


class ArticleCreateView(
    LoginRequiredMixin, AuthorsMixin, ActionMixin, FormValidMixin, FieldsMixin, CreateView
):
    model = Blog
    template_name = "accounts/articleCreate.html"
    success_message = "مقاله با موفقیت ساخته شد."


class ArticleUpdateView(
    LoginRequiredMixin,
    AuthorsMixin,
    ActionMixin,
    DraftEditMixin,
    UpdateAccessMixin,
    FormValidMixin,
    FieldsMixin,
    UpdateView,
):
    model = Blog
    template_name = "accounts/articleUpdate.html"
    success_message = "با موفقیت بروزرسانی شد."


# show updated or created successfully message
class ArticleDetailView(ActionMixin, DetailView):
    model = Blog
    template_name = "accounts/article_detail.html"


class ArticleDeleteView(LoginRequiredMixin, AuthorsMixin, DeleteArticleMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("accounts:list")
    template_name = "accounts/articleDelete.html"


class ArticlePreviewView(PreviewMixin, DetailView):
    def get_object(self, *args, **kwargs):
        slug = self.kwargs.get("slug")
        return get_object_or_404(Blog, slug=slug)

    template_name = "blog/article_Detail.html"


class CategoryListView(LoginRequiredMixin, StaffMixin, ListView):
    template_name = "accounts/category_list.html"
    queryset = Category.objects.all()


class CategoryCreateView(
    LoginRequiredMixin, StaffMixin, ActionMixin, CreateView
):
    fields = "__all__"
    model = Category
    template_name = "accounts/category_create.html"
    success_message = "دسته بندی با موفقیت ساخته شد."


# show updated or created successfully message
class CategoryDetailView(LoginRequiredMixin, StaffMixin, ActionMixin, DetailView):
    model = Category
    template_name = "accounts/article_detail.html"


class CategoryUpdateView(
    LoginRequiredMixin,
    StaffMixin,
    ActionMixin,
    UpdateView,
):
    model = Category
    fields = "__all__"
    template_name = "accounts/category_update.html"
    success_message = "با موفقیت بروزرسانی شد."


class CategoryDeleteView(LoginRequiredMixin, StaffMixin, ActionMixin, DeleteView):
    model = Category
    success_url = reverse_lazy("accounts:cat_list")
    template_name = "accounts/category_delete.html"


'''
Comment System
'''


class CommentListView(LoginRequiredMixin, StaffMixin, ListView):
    template_name = "accounts/comment_list.html"
    queryset = Comment.objects.all()


class CommentUpdateView(
    LoginRequiredMixin,
    StaffMixin,
    UpdateView,
):
    model = Comment
    fields = "__all__"
    template_name = "accounts/comment_update.html"
    success_url = reverse_lazy("accounts:comment_list")


class CommentDeleteView(LoginRequiredMixin, StaffMixin, DeleteView):
    model = Comment
    success_url = reverse_lazy("accounts:comment_list")
    template_name = "accounts/comment_delete.html"


class CommentAcceptView(LoginRequiredMixin, StaffMixin, UpdateView):
    model = Comment
    fields = ["display"]
    template_name = "accounts/comment_accept.html"
    success_url = reverse_lazy("accounts:comment_list")


'''
end of comment system
'''


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_object(self, *args, **kwargs):
        return User.objects.get(pk=self.request.user.pk)

    model = User
    template_name = "accounts/profileUpdate.html"
    success_url = reverse_lazy("accounts:profile")
    form_class = ProfileForm


class LogEventsListView(ListView):
    queryset = Logs.objects.all()
    template_name = "accounts/log.html"


# registration and user activation
class RegisterCreateView(CreateView):
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        current_site = get_current_site(request)
        mail_subject = "Activate your blog accounts."
        message = render_to_string(
            "accounts/acc_active_email.html",
            {
                "user": user,
                "domain": current_site.domain,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": account_activation_token.make_token(user),
            },
        )
        to_email = form.cleaned_data.get("email")
        email = EmailMessage(mail_subject, message, to=[to_email])
        email.send()
        return redirect("register-pending")

    form_class = SignupForm
    template_name = "accounts/register_form.html"


def activate(req, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect("register-complete")
    else:
        return HttpResponse("فعالسازی اکانت ناموفق بود.")

templates/accounts/acc_active_email.html
{% autoescape off %}
{{ user.username }} عزیز سلام,
برای تایید عضویت روی لینک زیر کلیک کن,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/article_detail.html
{% extends 'accounts/base.html' %}
{% block main %}
	<div class="container">
		<div class="row text-right">
			<div class="col-md-8 mt-3 mx-auto mt-5">
				<div class="card card-success">
					<div class="card-header">
					<h3 class="card-title float-right">انجام شد.</h3>
					</div>
					<div class="form-group p-3">
            {% if messages %}
            <ul class="messages">
              {% for message in messages %}
              <li>{{ message }}</li>
              {% endfor %}
            </ul>
            {% endif %}
          </div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/accounts/category_create.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main %}
    <div class="mt-2 card card-primary">
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            {{ form.title|as_crispy_field }}
                        </div>
                        <div class="col-md-6">
                            {{ form.slug|as_crispy_field }}
                        </div>
                        <div class="col-md-12">
                            {{ form.parent|as_crispy_field }}
                        </div>
                        <div class="col-md-6">
                            {{ form.display|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.position|as_crispy_field }}
                        </div>
                    </div>
                    <button class="btn btn-primary">ثبت</form>
        </form>
    </div>
{% endblock main %}

templates/accounts/category_list.html
{% extends 'accounts/base.html' %}

{% block main %}
    <div class="row">
        <div class="col-12">
            <div class="card mt-4">
                {% if object_list %}
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>عنوان</th>
                                <th class='d-none d-lg-table-cell'>نمایش</th>
                                <th class='d-none d-lg-table-cell'>دسته بندی والد</th>
                                <th class='d-none d-lg-table-cell'>انجام عملیات</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for category in object_list %}
                                    <tr>
                                        <td>
                                            <a href="{% url "accounts:cat_update" category.pk %}">
                                                {{ category.title }}
                                            </a>
                                        </td>
                                        <td>
                                        {% if category.display %}
                                            <p>فعال</p>
                                        {% else %}
                                            <p>غیرفعال</p>
                                        {% endif %}
                                        </td>
                                        <td>
                                        {% if category.parent %}
                                            {{ category.parent }}
                                        {% else %}
                                           والدی ندارد
                                        {% endif %}
                                        </td>
                                        <td>
                                            <a href="{% url 'accounts:cat_update' category.pk %}">
                                                <span class="badge badge-primary">ویرایش دسته بندی</span><br>
                                            </a>
                                            <a href="{% url 'accounts:cat_delete' category.pk %}">
                                                <span class="badge badge-danger">حذف دسته بندی</span><br>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="card-body table-responsive text-right p-6">
                        <h3>دسته بندی موجود نیست.</h3>
                    </div>
                {% endif %}
                    <!-- /.card-body -->
            </div>
        <!-- /.card -->
        </div>
    </div>
{% endblock %}

templates/accounts/comment_delete.html
{% extends 'accounts/base.html' %}
{% block main %}
	<div class="container">
		<div class="row text-right">
			<div class="col-md-8 mt-3 mx-auto mt-5">
				<div class="card card-danger">
					<div class="card-header">
					<h3 class="card-title float-right">حذف نظر</h3>
					</div>
					<div class="form-group p-3">
						<form method="POST">{% csrf_token %}
							<p class="text-danger">آیا مایل هستید نظر {{object.name}} حذف شود؟</p>
							<input type='submit' class="btn btn-danger" value='حذف نظر'>
							<a href="{% url 'accounts:comment_list' %}"><span class="btn btn-success">انصراف</span></a>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/accounts/comment_list.html
{% extends 'accounts/base.html' %}

{% block main %}
    <div class="row">
        <div class="col-12">
            <div class="card mt-4">
                {% if object_list %}
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>متن</th>
                                <th>فرستنده</th>
                                <th>ایمیل</th>
                                <th>پست</th>
                                <th class='d-none d-lg-table-cell'>انجام عملیات</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for comment in object_list %}
                                    <tr>
                                        <td>
                                            <a href="{% url "accounts:comment_update" comment.pk %}">
                                                {{ comment.body|safe }}
                                            </a>
                                        </td>
                                        <td>
                                            <p>{{ comment.name }}</p>
                                        </td>
                                        <td>
                                            <p>{{ comment.email }}</p>
                                        </td>
                                        <td>
                                            <p>{{ comment.post }}</p>
                                        </td>
                                        <td>
                                            {% if comment.display == False %}
                                            <a href="{% url 'accounts:comment_accept' comment.pk %}">
                                                <span class="badge badge-primary">تایید نظر</span>
                                            {% endif %}
                                            <a href="{% url 'accounts:comment_delete' comment.pk %}">
                                                <span class="badge badge-danger">حذف</span>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="card-body table-responsive text-right p-6">
                        <h3>نظری موجود نیست.</h3>
                    </div>
                {% endif %}
                    <!-- /.card-body -->
            </div>
        <!-- /.card -->
        </div>
    </div>
{% endblock %}

templates/accounts/comment_update.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main %}
    <div class="mt-2 card card-primary">    
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-12">
                            {{ form.body|as_crispy_field }}
                        </div>
                        <div class="col-md-6">
                            {{ form.name|as_crispy_field }}
                        </div>
                        <div class="col-md-6">
                            {{ form.email|as_crispy_field }}
                        </div>
                        <div class="col-md-6">
                            {{ form.post|as_crispy_field }}
                        </div>
                        <div class="col-md-6">
                            {{ form.display|as_crispy_field }}
                        </div>
                    </div>
                    <button class="btn btn-primary">ثبت</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/accounts/log.html
{% extends 'accounts/base.html' %}
{% load tags %}

{% block main %}
    <div class="row">
        <div class="col-12">
            <div class="card mt-4">
                {% if object_list %}
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>عنوان تغییر</th>
                                <th class='d-none d-lg-table-cell'>کلاس</th>
                                <th class='d-none d-lg-table-cell'>زمان تغییر</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for entry in object_list %}
                                    <tr>
                                        <td>
                                            <a href="{{ entry.log.get_admin_url }}">{{ entry.log }}</a>
                                            </a>
                                        </td>
                                        <td>
                                            {% if entry.log.content_type %}
                                                {{ entry.log.content_type.name }}
                                            {% else %}
                                                نامشخص
                                            {% endif %}
                                        </td>
                                        <td>
                                            {{ entry.jpublished }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="card-body table-responsive text-right p-6">
                        <h3>لاگی موجود نیست.</h3>
                    </div>
                {% endif %}
                    <!-- /.card-body -->
            </div>
        <!-- /.card -->
        </div>
    </div>
{% endblock %}

templates/accounts/login.html
{% extends 'accounts/base_login.html' %}
{% load static %}
{% load widget_tweaks %}
{% block form %}
<form class="login100-form validate-form" method='POST'>{% csrf_token %}
	<span class="login100-form-title p-b-26 my_font">
		خوش آمدید
	</span>
	<span class="login100-form-title p-b-48">
		<i class="zmdi zmdi-font"></i>
	</span>

	<div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
		{{ form.username|add_class:"input100" }}
		{% if form.username.errors %}
			{% for error in form.username.errors %}
				<span class="my_font">{{error}}</span>
			{% endfor %}
		{% endif %}
		<span class="focus-input100" data-placeholder="نام کاربری"></span>
	</div>

	<div class="wrap-input100 validate-input" data-validate="Enter password">
		<span class="btn-show-pass">
			<i class="zmdi zmdi-eye"></i>
		</span>
		{{ form.password|add_class:"input100" }}
		<span class="focus-input100" data-placeholder="کلمه عبور"></span>
		{% if form.username.errors %}
			{% for error in form.username.errors %}
				<span class="my_font">{{error}}</span>
			{% endfor %}
		{% endif %}
	</div>
	{% if form.non_field_errors %}
		{% for error in form.non_field_errors  %}
			<span class="my_font">{{ error }}</span>
		{% endfor %}
	{% endif %}
	<a href="{% url 'password_reset' %}">فراموشی رمز</a>
	<a href="{% url 'register' %}">ثبت نام</a>
	<div class="container-login100-form-btn">
		<div class="wrap-login100-form-btn">
			<div class="login100-form-bgbtn"></div>
			<button class="login100-form-btn my_font">
				ورود
			</button>
		</div>
	</div>
</form>
{% endblock %}

templates/accounts/password_change_form.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main %}
    <div class="mt-2 card card-primary">    
        <form method="POST">{% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            {{ form.old_password|as_crispy_field }}
                        </div>
                        <div class="col-md-6"></div>
                        <div class="col-md-6">
                            {{ form.new_password1|as_crispy_field }}
                        </div>
                        <div class="col-md-12">
                            {{ form.new_password2|as_crispy_field }}
                        </div>
                    </div>
                    <button class="mt-1 btn btn-danger">تغییر کلمه عبور</button></form>
        </form>
    </div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'accounts/base_login.html' %}
{% load static %}
{% load widget_tweaks %}
{% block form %}
<form class="login100-form validate-form" method='POST'>{% csrf_token %}
	<span class="login100-form-title p-b-26 my_font">
		خوش آمدید
	</span>
	<span class="login100-form-title p-b-48">
		<i class="zmdi zmdi-font"></i>
	</span>

	<div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
		{{ form.new_password1|add_class:"input100" }}
		{% if form.new_password1.errors %}
			{% for error in form.newpassword1.errors %}
				<span class="my_font">{{error}}</span>
			{% endfor %}
		{% endif %}
		<span class="focus-input100" data-placeholder="پسورد"></span>
	</div>
    <div class="wrap-input100 validate-input">
		{{ form.new_password2|add_class:"input100" }}
		{% if form.new_password2.errors %}
			{% for error in form.newpassword2.errors %}
				<span class="my_font">{{error}}</span>
			{% endfor %}
		{% endif %}
		<span class="focus-input100" data-placeholder="تایید پسورد"></span>
	</div>
	<div class="container-login100-form-btn">
		<div class="wrap-login100-form-btn">
			<div class="login100-form-bgbtn"></div>
			<button class="login100-form-btn my_font">
				تغییر رمز
			</button>
		</div>
	</div>
</form>
{% endblock %}

templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/accounts/password_reset_form.html
{% extends 'accounts/base_login.html' %}
{% load static %}
{% load widget_tweaks %}
{% block form %}
<form class="login100-form validate-form" method='POST'>{% csrf_token %}
	<span class="login100-form-title p-b-26 my_font">
		خوش آمدید
	</span>
	<span class="login100-form-title p-b-48">
		<i class="zmdi zmdi-font"></i>
	</span>

	<div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
		{{ form.email|add_class:"input100" }}
		{% if form.email.errors %}
			{% for error in form.email.errors %}
				<span class="my_font">{{error}}</span>
			{% endfor %}
		{% endif %}
		<span class="focus-input100" data-placeholder="ایمیل"></span>
	</div>
	<div class="container-login100-form-btn">
		<div class="wrap-login100-form-btn">
			<div class="login100-form-bgbtn"></div>
			<button class="login100-form-btn my_font">
				ارسال ایمیل
			</button>
		</div>
	</div>
</form>
{% endblock %}

templates/accounts/register_done.html
{% extends 'accounts/base_login.html' %}
{% load static %}
{% load widget_tweaks %}
{% block form %}
<span class="login100-form-title p-b-26 my_font">
    تایید
</span>
<span class="login100-form-title p-b-48">
    <i class="zmdi zmdi-font"></i>
</span>

<div class="container-login100-form-btn">
    <div class="wrap-login100-form-btn">
        <div class="login100-form-bgbtn"></div>
        <button class="login100-form-btn my_font">
           ایمیل ارسال شد. پوشه اسپم رو چک کن.
        </button>
    </div>
</div>
{% endblock %}