api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from .views import ArticleListApiView, ArticleDetailApiView, UserListApiView, UserDetailApiView, RevokeTokenApiView,\
    CategoryListAPIView, CategoryDetailAPIVIEW
app_name = "api"

urlpatterns = [
    path("token/", obtain_auth_token, name="token"),
    path("revoke/", RevokeTokenApiView.as_view(), name="token"),
    path("", ArticleListApiView.as_view(), name="list"),
    path("detail/<str:slug>/", ArticleDetailApiView.as_view(), name="detail"),
    path("categories/", CategoryListAPIView.as_view(), name="cat_list"),
    path("categories/detail/<str:slug>/", CategoryDetailAPIVIEW.as_view(), name="cat_detail"),
    path("users/", UserListApiView.as_view(), name="user_list"),
    path("users/<int:pk>", UserDetailApiView.as_view(), name="user_detail"),
]

blog/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, CategoryListView, UserListView, SearchListView, CommentDetailView

app_name = "blog"
urlpatterns = [
    path("", ArticleListView.as_view(), name="index"),
    path("page/<int:page>/", ArticleListView.as_view(), name="index"),
    path("search/", SearchListView.as_view(), name="search"),
    path("search/<int:page>/", SearchListView.as_view(), name="search"),
    path("", ArticleListView.as_view(), name="index"),
    path("<str:slug>/", ArticleDetailView.as_view(), name="single"),
    path("comment/<str:slug>", CommentDetailView.as_view(), name="comment"),
    path("category/<str:slug>/", CategoryListView.as_view(), name="category"),
    path("category/<str:slug>/page/<int:page>/", CategoryListView.as_view(), name="category"),
    path("user/<str:slug>/", UserListView.as_view(), name="user"),
    path("user/<str:slug>/page/<int:page>/", UserListView.as_view(), name="user"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from accounts.views import Login, RegisterPendingView, RegisterCompleteView
from accounts.views import RegisterCreateView, activate

handler500 = 'exception_handling.views.handler500'
handler404 = 'exception_handling.views.handler404'

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("register/", RegisterCreateView.as_view(), name="register"),
    path("register/pending/", RegisterPendingView.as_view(), name="register-pending"),
    path("register/complete/", RegisterCompleteView.as_view(), name="register-complete"),
    path("activate/<str:uidb64>/<str:token>/", activate, name="activate"),
    path("accounts/", include("accounts.urls"), name="home"),
    path("admin/doc/", include("django.contrib.admindocs.urls"), name="admin_doc"),
    path("admin/", admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path("api/", include("api.urls"), name="api"),
    path("pages/", include("pages.urls"), name="pages"),
    path("", include("django.contrib.auth.urls")),
    path("", include("blog.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils import timezone
from django.utils.html import format_html
from django.urls import reverse
from hitcount.models import HitCount
from extensions.utils import to_jalali, unique_slug
from accounts.models import User
from core.models import TimeStampedModel


class PublishedArticle(models.Manager):
    def published(self):
        return self.filter(status="p")


class ShownCategory(models.Manager):
    def shown(self):
        return self.filter(display=True)


class PublishedComment(models.Manager):
    def published(self):
        return self.filter(display=True)


class Category(models.Model):
    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ["parent__id", "position"]

    def __str__(self):
        return self.title

    title = models.CharField(max_length=255, default="", verbose_name="دسته بندی")
    parent = models.ForeignKey(
        "self",
        related_name="children",
        default=None,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="دسته والد",
    )
    slug = models.SlugField(
        max_length=20, unique=True, allow_unicode=True, verbose_name="نامک"
    )
    display = models.BooleanField(
        verbose_name="نمایش",
        default=True,
    )
    position = models.IntegerField(verbose_name="جایگاه", default="0")

    objects = ShownCategory()

    def get_absolute_url(self):
        return reverse("accounts:cat_detail", kwargs={"slug": self.slug})


class Blog(TimeStampedModel):
    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ["-published"]

    STATUS_CHOICES = (
        ("d", "پیش نویس"),
        ("p", "منتشر شده"),
        ("w", "در انتظار تایید"),
        ("r", "رد شده"),
    )
    title = models.CharField(max_length=255, verbose_name="عنوان")
    slug = models.SlugField(
        blank=True, unique=True, max_length=20, allow_unicode=True, verbose_name="نامک"
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        related_name="articles",
        verbose_name="نویسنده",
    )
    description = models.TextField(max_length=1000, verbose_name="توضیحات")
    image = models.ImageField(upload_to="images", blank=True, null=True, verbose_name="تصویر شاخص")
    published = models.DateTimeField(default=timezone.now, verbose_name="تاریخ انتشار")
    is_special = models.BooleanField(
        verbose_name="مقاله ویژه",
        default=False,
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name="وضعیت")
    category = models.ManyToManyField(Category, related_name="articles", verbose_name="دسته بندی")
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count')

    def category_list(self):
        return "، ".join([i.title for i in self.category.shown()])

    def jpublished(self):
        #convert Gregorian to jalali date
        return to_jalali(self.published)

    def thumb(self):
        if self.image:
            return format_html(
                f"<img src='{self.image.url}' height=80px width=100px style='border-radius:20px;'>"
            )

    def __str__(self):
        return self.title

    def show_url(self):
        if self.slug:
            url = reverse("blog:single", kwargs={"slug": self.slug})
            response = format_html(f'<a href="{url}">{self.title}</a>')
            return response
        return 'برای مشاهده لینک مقاله ابتدا باید آن را منشتر کنید.'

    def get_absolute_url(self):
        return reverse("accounts:detail", kwargs={"slug": self.slug})

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None, *args, **kwargs):
        # avoid regenerating slug.
        if not self.pk:
            title = self.title
            max_length = self._meta.get_field('slug').max_length
            self.slug = unique_slug(title, max_length, Blog)
        super().save(*args, **kwargs)

    objects = PublishedArticle()

    jpublished.short_description = "زمان انتشار"
    category_list.short_description = "دسته بندی"
    thumb.short_description = "تصویر بندانگشتی"
    show_url.short_description = "نمایش مقاله"


class Comment(TimeStampedModel):
    class Meta:
        verbose_name = "نظر"
        verbose_name_plural = "نظرات"
        ordering = ["created"]

    post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comments", verbose_name="نظر")
    name = models.CharField(max_length=50, verbose_name="نام")
    email = models.EmailField(verbose_name="ایمیل")
    body = models.TextField(max_length=1000, verbose_name="متن نظر")
    display = models.BooleanField(
        verbose_name="نمایش",
        default=False,
    )

    def __str__(self):
        return self.body

    def jpublished(self):
        #convert Gregorian to jalali date
        return to_jalali(self.created)

    def get_absolute_url(self):
        return reverse("blog:comment", kwargs={"slug": self.post.slug})

    objects = PublishedComment()

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        post = kwargs.pop("post")
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields["post"].initial = post
        self.fields["post"].disabled = True

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body', 'post')

blog/views.py
from django.views.generic import ListView, CreateView, TemplateView
from django.shortcuts import get_object_or_404
from hitcount.views import HitCountDetailView

from .forms import CommentForm
from .mixins import CommentFormValidMixin
from .models import Blog, Category
from core.mixins import SearchActionMixin
from accounts.models import User


class ArticleListView(ListView):
    queryset = Blog.objects.published().select_related("author")
    template_name = "blog/article_list.html"
    paginate_by = 2
    

class SearchListView(SearchActionMixin, ListView):
    model = Blog
    template_name = "blog/search_list.html"
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q')
        return context


class ArticleDetailView(CreateView, CommentFormValidMixin, HitCountDetailView):
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        slug = self.kwargs.get("slug")
        # get id of the post -> required for post field on Comment model.
        post = get_object_or_404(Blog.objects.published(), slug=slug).id
        kwargs["post"] = post
        return kwargs

    def get_object(self, *args, **kwargs):
        slug = self.kwargs.get("slug")
        return get_object_or_404(Blog.objects.published(), slug=slug)

    template_name = "blog/article_detail.html"
    form_class = CommentForm
    count_hit = True


class CategoryListView(ListView):
    def get_queryset(self):
        slug = self.kwargs.get("slug")
        category = get_object_or_404(Category.objects.shown(), slug=slug)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        slug = self.kwargs.get("slug")
        category = get_object_or_404(Category.objects.shown(), slug=slug)
        context = super().get_context_data(**kwargs)
        context["category"] = category
        return context

    template_name = "blog/category_list.html"
    paginate_by = 2


class UserListView(ListView):
    def get_queryset(self):
        username = self.kwargs.get("slug")
        user = get_object_or_404(User, username=username)
        return user.articles.all()

    def get_context_data(self, **kwargs):
        username = self.kwargs.get("slug")
        user = get_object_or_404(User, username=username)
        context = super().get_context_data(**kwargs)
        context["user"] = user
        return context

    template_name = "blog/user_list.html"
    paginate_by = 2


# show success message
class CommentDetailView(TemplateView):

    template_name = "blog/comment_submit.html"
    model = Blog

templates/blog/articleList.html
{% extends 'blog/list.html' %}
{% load tags %}
{% block head_title %}
    home page
{% endblock %}
{% block head_description %}
    صفحه خانگی وب سایت ما اینجا می باشد.
{% endblock %}
{% block next_page %}
    {% url 'blog:index' page_obj.next_page_number %}
{% endblock %}
{% block previous_page %}
    {% url 'blog:index' page_obj.previous_page_number %}
{% endblock %}

templates/blog/article_Detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load hitcount_tags %}

{% block title %}
    {{ object.title }}
{% endblock %}
{% block head_title %}
    {{object.title}}
{% endblock %}
{% block blog_post %}
    <div class="card mb-1">
        {% if article.image %}
            <img class="card-img-top" src="{{ object.image.url }}"  alt="{{ object.slug}}" style='height:300px;' />
        {% endif %}
        <div class="card-body">

            <div class="small text-muted">
                {{ object.jpublished }}
                | تعداد بازدید: {% get_hit_count for object %}
            </div>

            {% if not article.is_special or user.is_specialuser or article.author == user %}
            {{ object.description|safe|linebreaks }}

            {% else %}
                <p>شما دسترسی ندارید.</p>
            {% endif %}

            {% for cat in object.category.shown %}
            <a href="{% url 'blog:category' cat.slug %}">#{{ cat.title }}</a>
            {% endfor %}

        </div>
    </div>


    <div class="card mb-12">
        <div class="card-header">نظرات</div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    <ul class="list-unstyled mb-0">
                        <li>
                           {% for comment in object.comments.published %}
                            <div class="comments" style="padding: 10px;">
                              <p>
                                {{ comment.name }}
                                <span class=" text-muted font-weight-normal">
                                  {{ comment.jpublished }}
                                </span>
                              </p>
                              {{ comment.body|safe|linebreaks }}
                            <hr>
                            </div>
                            {% empty %}
                                اولین نظر را ثبت کن!
                            {% endfor %}
                            
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!--form-->
        <div class="mt-2 card card-primary">
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            {{ form.name|as_crispy_field }}
                        </div>
                        <div class="col-md-6">
                            {{ form.email|as_crispy_field }}
                        </div>
                        <div class="col-md-12">
                            {{ form.body|as_crispy_field }}
                        </div>
                                   </div>
                    </div>
                <button class="btn btn-primary">ثبت</button></form>
        </form>
    </div></div>

{% endblock %}

templates/blog/article_List.html
{% extends 'blog/base_list.html' %}
{% load tags %}
{% block head_title %}
    {% site_profile 'title' %}
{% endblock %}
{% block head_description %}
    {% site_profile 'description' %}
{% endblock %}
{% block next_page %}
    {% url 'blog:index' page_obj.next_page_number %}
{% endblock %}
{% block previous_page %}
    {% url 'blog:index' page_obj.previous_page_number %}
{% endblock %}

templates/blog/base.html
{% load static %}
{% load tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
            {% site_profile 'title' %}
            {% endblock %}
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'account/blog/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static '/blog/css/navbar.css' %}" rel="stylesheet" />
        <link href="{% static '/blog/css/styles.css' %}" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet">
        <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'blog:index' %}">
                    {% site_profile 'title' %}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% block nav-items %}
                            {% nav_items %}
                        {% endblock %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">{% block head_title %}{% endblock %}</h1>
                    <p class="lead mb-0">{% block head_description %}{% endblock %}</p>
                </div>
            </div>
        </header>
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    {% block blog_post %}
                    {% endblock %}
                <!-- Side widgets--></div>
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">جستجو</div>
                        <div class="card-body">
                            <form method="GET" action="{% url 'blog:search' %}">
                              <div class="input-group">
                                <input class="form-control" type="text" value="{{q}}" name="q" placeholder="قسمتی از عنوان مقاله..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="submit">یافتن!</button>
                              </div>
                            </form>
                        </div>
                    </div>
                    <!-- left widgets-->
                    <div class="card mb-4">
                        <div class="card-header">دسته بندی ها</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <ul class="list-unstyled mb-0">
                                        {% navbar_cat %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-4">
                        <div class="card-header">پربازدیدترین ها</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <ul class="list-unstyled mb-0">
                                        {% top_posts %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>


                    <!-- left sidebar handled by django-->
                    {% widget 'left' %}
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
        <!-- Template tags -->
            <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    {% widget 'foot1' %}
                </div>
                <div class="col-lg-4">
                    {% widget 'foot2' %}
                </div>
                <div class="col-lg-4">
                    {% widget 'foot3' %}
                </div>
            </div>
        </div>
            <div class="container"><p class="m-0 text-center text-white">تمامی حقوق برای این وبسایت محفوظ می باشد.</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

templates/blog/base_list.html
{% extends 'blog/base.html' %}
{% load tags %}
{% load hitcount_tags %}

{% block head_title %}
لیست مقالات
{% endblock %}
{% block head_description %}{% endblock %}
{% block blog_post %}
    {% for article in object_list %}
        <div class="card mb-4">
            {% if article.image %}
                <a href="{% url 'blog:single' article.slug %}"><img class="card-img-top" src="{{ article.image.url }}"  alt="{{ article.slug}}" style='height:300px;' /></a>
            {%endif %}
            <div class="card-body">
                <div class="small text-muted">
                    {% if article.is_special %}
                        <span class="badge" style="background-color: #a21515;">مقاله ویژه</span><br>
                    {% endif %}
                    {{ article.jpublished }}
                    | تعداد بازدید: {% get_hit_count for article %}

                </div>
                <a href="{% url 'blog:single' article.slug %}">
                    <h2 class="card-title">
                        {{ article.title }}
                    </h2>
                </a>
                <p class="card-text">
                    {% if not article.is_special or user.is_specialuser or article.author == user %}
                        {{ article.description|safe|linebreaks|truncatewords:'20' }}
                    {% else %}
                        <p>شما دسترسی ندارید.</p>
                    {% endif %}
                </p>
                    <sm>
                        <i class="bi bi-person-circle"></i> نویسنده: 
                        <a href="{% url 'blog:user' article.author.username%}">
                            {% if article.author.get_full_name %}
                                {{ article.author.get_full_name }}
                            {% else %}
                                نویسنده سایت
                            {% endif %}
                        </a>
                    </sm>
                <i class="bi bi-card-list"></i> دسته بندی:
                {% for cat in article.category.shown %}
                    <a href="{% url 'blog:category' cat.slug %}">
                        #{{ cat.title }}
                    </a>
                {% endfor %}
            </div>
        </div>
    {% empty %}
    <h3>
        <i class="bi bi-file-x-fill"></i>
        مقاله ای موجود نیست.
    </h3>    {% endfor %}
    {% if page_obj.has_next %}
        <a href="{% block next_page %}{% endblock %}">مقالات قدیمی تر</a>
    {% endif %}
    {% if page_obj.has_previous %}
    <a href="{% block previous_page %} {% endblock %}">مقالات جدید تر</a>
{% endif %}
{% endblock %}

templates/blog/categoryList.html
{% extends 'blog/list.html' %}
{% load tags %}
{% block head_title %}
{{ category.title }}
{% endblock %}
{% block head_description %}
صفحه دسته بندی {{ category.slug }} وب سایت ما اینجا می باشد.
{% endblock %}
{% block next_page %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}
{% block previous_page %}
    {% url 'blog:category' category.slug  page_obj.previous_page_number %}
{% endblock %}

templates/blog/category_list.html
{% extends 'blog/base_list.html' %}
{% load tags %}

{% block title %}
{{ block.super }}
 | لیست مقالات دسته بندی {{ category.title }}
{% endblock %}

{% block head_title %}
{{ category.title }}
{% endblock %}

{% block head_description %}
صفحه دسته بندی {{ category.slug }} وب سایت ما اینجا می باشد.
{% endblock %}

{% block next_page %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

{% block previous_page %}
    {% url 'blog:category' category.slug  page_obj.previous_page_number %}
{% endblock %}

templates/blog/comment_submit.html
{% extends 'blog/base.html' %}

{% block title %}
    نظرات
{% endblock %}

{% block head_title %}
    ثبت نظر
{% endblock %}

{% block blog_post %}
    <div class="card mb-1">
        <div class="card-body">
        {% if request.user.is_superuser %}
            <h3>نظر ثبت شد.</h3>
        {% else %}
            <h3>نظر ثبت شد و در انتظار تایید مدیر می باشد.</h3>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load tags %}
{% block head_title %}
home page
{% endblock %}
{% block head_description %}{% endblock %}
{% block blog_post %}
    {% for article in object_list %}
        <div class="card mb-4">
            <a href="{% url 'blog:single' article.slug %}"><img class="card-img-top" src="{{ article.image.url }}"  alt="{{ article.slug}}" style='height:300px;' /></a>
            <div class="card-body">
                <div class="small text-muted">
                    {% if article.is_special %}
                        <span class="badge" style="background-color: #a21515;">مقاله ویژه</span><br>
                    {% endif %}
                    {{ article.jpublished }}
                </div>
                <a href="{% url 'blog:single' article.slug %}">
                    <h2 class="card-title">
                        {{ article.title }}
                    </h2>
                </a>
                    <p class="card-text">
                        {% if article.is_special %}
                            {% if user.is_authenticated and user.is_specialuser or user.is_superuser or user.is_staff or article.author == user %}
                                {{ article.description|safe|linebreaks|truncatewords:'20' }}
                            {% else %}
                                <p>شما دسترسی ندارید.</p>
                            {% endif %}
                        {% else %}
                            {{ article.description|safe|linebreaks|truncatewords:'20' }}
                        {% endif %}
                    </p>
                <a href="{% url 'blog:user' article.author.username%}">
                    <sm>
                        نویسنده: {{ article.author.get_full_name }}
                    </sm>
                </a>
                {% for cat in article.category.shown %}
                    <a href="{% url 'blog:category' cat.slug %}">
                        #{{ cat.title }}
                    </a>
                {% endfor %}
            </div>
        </div>
    {% empty %}
    <h1>مقاله ای موجود نیست.</h1>
    {% endfor %}
    {% if page_obj.has_next %}
        <a href="{% block next_page %}{% endblock %}">مقالات قدیمی تر</a>
    {% endif %}
    {% if page_obj.has_previous %}
    <a href="{% block previous_page %} {% endblock %}">مقالات جدید تر</a>
{% endif %}
{% endblock %}

templates/blog/searchList.html
{% extends 'blog/list.html' %}
{% load tags %}
{% block head_title %}
    Search
{% endblock %}
{% block head_description %}
    جستجو برای مقالات حاوی '{{ q }}'
{% endblock %}
{% block next_page %}
    {% url 'blog:search' page_obj.next_page_number %}?q={{ q }}
{% endblock %}
{% block previous_page %}
    {% url 'blog:search' page_obj.previous_page_number %}?q={{ q }}
{% endblock %}

templates/blog/search_list.html
{% extends 'blog/base_list.html' %}
{% load tags %}

{% block title %}
{{ block.super }}
 | مقالات حاوی {{ q }}
{% endblock %}

{% block head_title %}
    Search
{% endblock %}

{% block head_description %}
    جستجو برای مقالات حاوی '{{ q }}'
{% endblock %}

{% block next_page %}
    {% url 'blog:search' page_obj.next_page_number %}?q={{ q }}
{% endblock %}

{% block previous_page %}
    {% url 'blog:search' page_obj.previous_page_number %}?q={{ q }}
{% endblock %}

templates/blog/userList.html
{% extends 'blog/list.html' %}
{% load tags %}
{% block head_title %}
{{ category.title }}
{% endblock %}
{% block head_description %} -->
مقالات {{ user.get_full_name }} اینجا می باشد.
{% endblock %}
{% block next_page %}
    {% url 'blog:user' user.username page_obj.next_page_number %}
{% endblock %}
{% block previous_page %}
    {% url 'blog:user' user.username  page_obj.previous_page_number %}
{% endblock %}

templates/blog/user_list.html
{% extends 'blog/base_list.html' %}
{% load tags %}

{% block title %}
{{ block.super }}
 | لیست مقالات {{ user.get_full_name }}
{% endblock %}

{% block head_title %}
{{ category.title }}
{% endblock %}

{% block head_description %} -->
مقالات {{ user.get_full_name }} اینجا می باشد.
{% endblock %}

{% block next_page %}
    {% url 'blog:user' user.username page_obj.next_page_number %}
{% endblock %}

{% block previous_page %}
    {% url 'blog:user' user.username  page_obj.previous_page_number %}
{% endblock %}